image: atlas/analysisbase:22.2.69

tester:
  variables:
    ABV_CM: 22.2.69
    ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  script:
    - set +e
    - source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/atlasLocalSetup.sh
    - asetup Athena,master,${ABV_CM}
    - python tests/test.py --matchingCriteria UseFTDeltaRvalues
  only:
    - master
  allow_failure: false
