name: Python Package using Conda

on:
  push:
    branches:
      - master
      - FixMatcherUsingFTDecisions
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: rootproject/root:6.22.06-conda
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install -e .
        conda install pytest
        pytest
    - name: Adding markdown
      if: ${{ failure() }}
      run: echo 'If changes on the references are expected and understood, update reference files with ```update_references.py```' >> $GITHUB_STEP_SUMMARY
